=== adriMB200/MotoGP-Desktop/xml/circuito.dtd
<!ELEMENT circuito (nombre, datosFisicos, evento, localizacion, tramos, resultado, clasificacionMundial, referencias, galeriaFotos, galeriaVideos)>

<!ELEMENT nombre (#PCDATA)>

<!ELEMENT datosFisicos (longitudCircuito, anchura)>
<!ELEMENT longitudCircuito (#PCDATA)>
<!ELEMENT anchura (#PCDATA)>

<!ELEMENT evento (fecha, hora, vueltas, patrocinador)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT hora (#PCDATA)>
<!ELEMENT vueltas (#PCDATA)>
<!ELEMENT patrocinador (#PCDATA)>

<!ELEMENT localizacion (localidad, pais, origen)>
<!ELEMENT localidad (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT origen (longitud, latitud, altitud)>
<!ELEMENT longitud (#PCDATA)>
<!ELEMENT latitud (#PCDATA)>
<!ELEMENT altitud (#PCDATA)>

<!ELEMENT tramos (tramo+)>
<!ELEMENT tramo (distancia, coordenadas, sector)>
<!ELEMENT distancia (#PCDATA)>
<!ATTLIST distancia unidad CDATA #REQUIRED>
<!ELEMENT coordenadas (longitud, latitud, altitud)>
<!ELEMENT sector (#PCDATA)>

<!ELEMENT resultado (vencedor, tiempo)>
<!ELEMENT vencedor (nombrePiloto)>
<!ELEMENT nombrePiloto (#PCDATA)>
<!ELEMENT tiempo (#PCDATA)>

<!ELEMENT clasificacionMundial (piloto+)>
<!ELEMENT piloto (posicion, nombre, puntos)>
<!ELEMENT posicion (#PCDATA)>
<!ELEMENT puntos (#PCDATA)>

<!ELEMENT referencias (ref+)>
<!ELEMENT ref (#PCDATA)>
<!ATTLIST ref href CDATA #REQUIRED>

<!ELEMENT galeriaFotos (foto+)>
<!ELEMENT foto (#PCDATA)>
<!ATTLIST foto
    fichero CDATA #REQUIRED
    titulo CDATA #REQUIRED>

<!ELEMENT galeriaVideos (video+)>
<!ELEMENT video (#PCDATA)>
<!ATTLIST video
    fichero CDATA #REQUIRED
    titulo CDATA #REQUIRED>

=== adriMB200/MotoGP-Desktop/xml/circuito.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE circuito SYSTEM "circuito.dtd">
<circuito>
    <nombre>MotorLand Aragón</nombre>

    <datosFisicos>
        <longitudCircuito>5078</longitudCircuito>
        <anchura>15</anchura>
    </datosFisicos>

    <evento>
        <fecha>2025-09-28</fecha>
        <hora>14:00</hora>
        <vueltas>23</vueltas>
        <patrocinador>Gran Premio Tissot de Aragón</patrocinador>
    </evento>

    <localizacion>
        <localidad>Alcañiz</localidad>
        <pais>España</pais>
        <origen>
            <longitud>-0.2136</longitud>
            <latitud>41.0792</latitud>
            <altitud>380</altitud>
        </origen>
    </localizacion>

    <tramos>
        <tramo>
            <distancia unidad="metros">1047</distancia>
            <coordenadas>
                <longitud>-0.2195</longitud>
                <latitud>41.0772</latitud>
                <altitud>375</altitud>
            </coordenadas>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidad="metros">2031</distancia>
            <coordenadas>
                <longitud>-0.2130</longitud>
                <latitud>41.0850</latitud>
                <altitud>385</altitud>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidad="metros">2000</distancia>
            <coordenadas>
                <longitud>-0.2136</longitud>
                <latitud>41.0792</latitud>
                <altitud>380</altitud>
            </coordenadas>
            <sector>3</sector>
        </tramo>
    </tramos>

    <resultado>
        <vencedor>
            <nombrePiloto>Francesco Bagnaia</nombrePiloto>
        </vencedor>
        <tiempo>41m 35.456s</tiempo>
    </resultado>

    <clasificacionMundial>
        <piloto>
            <posicion>1</posicion>
            <nombre>Francesco Bagnaia</nombre>
            <puntos>250</puntos>
        </piloto>
        <piloto>
            <posicion>2</posicion>
            <nombre>Marc Márquez</nombre>
            <puntos>235</puntos>
        </piloto>
        <piloto>
            <posicion>3</posicion>
            <nombre>Jorge Martín</nombre>
            <puntos>228</puntos>
        </piloto>
    </clasificacionMundial>

    <referencias>
        <ref href="https://www.motorlandaragon.com/">Página oficial de MotorLand Aragón</ref>
        <ref href="https://es.wikipedia.org/wiki/MotorLand_Arag%C3%B3n">Wikipedia: MotorLand Aragón</ref>
        <ref href="https://www.motogp.com/es/gp-results/2024/ara">Resultados oficiales de MotoGP</ref>
    </referencias>

    <galeriaFotos>
        <foto fichero="media/aragon_pano.jpg" titulo="Vista panorámica del circuito">aragon_pano.jpg</foto>
        <foto fichero="media/aragon_recta.jpg" titulo="Recta de meta de MotorLand">aragon_recta.jpg</foto>
    </galeriaFotos>

    <galeriaVideos>
        <video fichero="media/aragon_resumen.mp4" titulo="Resumen de la carrera">aragon_resumen.mp4</video>
    </galeriaVideos>

</circuito>
