=== adriMB200/MotoGP-Desktop/xml/circuito.xsd
<?xml version="1.0" encoding="Windows-1252"?>
<xs:schema xmlns="http://tempuri.org/circuito" elementFormDefault="qualified"
	targetNamespace="http://tempuri.org/circuito" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="circuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="datosFisicos" />
				<xs:element ref="evento" />
				<xs:element ref="localizacion" />
				<xs:element ref="tramos" />
				<xs:element ref="resultado" />
				<xs:element ref="clasificacionMundial" />
				<xs:element ref="referencias" />
				<xs:element ref="galeriaFotos" />
				<xs:element ref="galeriaVideos" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombre" type="xs:string" />
	<xs:element name="datosFisicos">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitudCircuito" />
				<xs:element ref="anchura" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="longitudCircuito">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="anchura">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="evento">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="fecha" />
				<xs:element ref="hora" />
				<xs:element ref="vueltas" />
				<xs:element ref="patrocinador" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="fecha" type="xs:string" />
	<xs:element name="hora" type="xs:string" />
	<xs:element name="vueltas" type="xs:string" />
	<xs:element name="patrocinador" type="xs:string" />
	<xs:element name="localizacion">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="localidad" />
				<xs:element ref="pais" />
				<xs:element ref="origen" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="localidad" type="xs:string" />
	<xs:element name="pais" type="xs:string" />
	<xs:element name="origen">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="longitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="latitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="altitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="tramos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="tramo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="tramo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="distancia" />
				<xs:element ref="coordenadas" />
				<xs:element ref="sector" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="distancia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="coordenadas">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="sector" type="xs:string" />
	<xs:element name="resultado">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="vencedor" />
				<xs:element ref="tiempo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="vencedor">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombrePiloto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombrePiloto" type="xs:string" />
	<xs:element name="tiempo" type="xs:string" />
	<xs:element name="clasificacionMundial">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="piloto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="piloto">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="posicion" />
				<xs:element ref="nombre" />
				<xs:element ref="puntos" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="posicion" type="xs:string" />
	<xs:element name="puntos" type="xs:string" />
	<xs:element name="referencias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="ref" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ref">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="href" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="galeriaFotos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="foto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="foto">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="fichero" type="xs:string" use="required" />
					<xs:attribute name="titulo" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="galeriaVideos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="video">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="fichero" type="xs:string" use="required" />
					<xs:attribute name="titulo" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== adriMB200/MotoGP-Desktop/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<circuito
    xsi:schemaLocation="http://www.uniovi.es circuito.xsd"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://www.uniovi.es">
    <nombre>Lusail International Circuit</nombre>

    <datosFisicos>
        <longitudCircuito unidad="metros">5380</longitudCircuito>
        <anchura unidad="metros">12</anchura>
    </datosFisicos>

    <evento>
        <fecha>2026-03-01</fecha>
        <hora>18:00</hora>
        <vueltas>22</vueltas>
        <patrocinador>Gran Premio de Qatar Airways</patrocinador>
    </evento>

    <localizacion>
        <localidad>Lusail</localidad>
        <pais>Qatar</pais>
        <origen>
            <longitud unidad="grados">51.4552</longitud>
            <latitud unidad="grados">25.4907</latitud>
            <altitud unidad="metros">1</altitud>
        </origen>
    </localizacion>

    <tramos>
        <tramo>
            <distancia unidad="metros">1800</distancia>
            <coordenadas>
                <longitud unidad="grados">51.4560</longitud>
                <latitud unidad="grados">25.4890</latitud>
                <altitud unidad="metros">1</altitud>
            </coordenadas>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidad="metros">1800</distancia>
            <coordenadas>
                <longitud unidad="grados">51.4580</longitud>
                <latitud unidad="grados">25.4920</latitud>
                <altitud unidad="metros">2</altitud>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidad="metros">1780</distancia>
            <coordenadas>
                <longitud unidad="grados">51.4552</longitud>
                <latitud unidad="grados">25.4907</latitud>
                <altitud unidad="metros">1</altitud>
            </coordenadas>
            <sector>3</sector>
        </tramo>
    </tramos>

    <resultado>
        <vencedor>
            <nombrePiloto>Marc Márquez</nombrePiloto>
        </vencedor>
        <tiempo>42m 40.123s</tiempo>
    </resultado>

    <clasificacionMundial>
        <piloto>
            <posicion>1</posicion>
            <nombre>Marc Márquez</nombre>
            <puntos>260</puntos>
        </piloto>
        <piloto>
            <posicion>2</posicion>
            <nombre>Francesco Bagnaia</nombre>
            <puntos>240</puntos>
        </piloto>
        <piloto>
            <posicion>3</posicion>
            <nombre>Jorge Martín</nombre>
            <puntos>230</puntos>
        </piloto>
    </clasificacionMundial>

    <referencias>
        <ref href="https://www.circuitlusail.com/">Página oficial de Lusail International Circuit</ref>
        <ref href="https://es.wikipedia.org/wiki/Circuito_Internacional_de_Lusail">Wikipedia:
            Circuito Internacional de Lusail</ref>
        <ref href="https://www.motogp.com/es/gp-results/2026/qatar">Resultados oficiales de MotoGP
            Qatar</ref>
    </referencias>

    <galeriaFotos>
        <foto fichero="media/lusail_noche.jpg" titulo="Circuito de Lusail iluminado">
            lusail_noche.jpg</foto>
        <foto fichero="media/marquez_lusail.jpg" titulo="Marc Márquez en Lusail">marquez_lusail.jpg</foto>
    </galeriaFotos>

    <galeriaVideos>
        <video fichero="media/lusail_resumen.mp4" titulo="Resumen de la carrera en Lusail">
            lusail_resumen.mp4</video>
    </galeriaVideos>

</circuito>
